apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: resetfollow
  namespace: default
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "0 28 18 * * *" # valid cron schedule