apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: unfollowtime
  namespace: default
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "0 44 22 * * *" # valid cron schedule